services:
  db:
    image: postgres:16-alpine
    container_name: flashcards_db
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: flashcards
      POSTGRES_PASSWORD: flashcards
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashcards -d flashcards"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
