spring:
  config:
    activate:
      on-profile: dev

  flyway:
    enabled: true
    # Ejecuta migraciones + semillas de desarrollo
    locations: classpath:db/migration,classpath:db/seed/dev

logging:
  level:
    # Puedes subir el nivel de detalle cuando depures en dev:
    com.fasterxml.jackson.databind: debug
    org.springframework.http.converter: trace
