spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: flash
    password: flash
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 8080