spring:
  application:
    name: flashcards-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: flashcards
    password: flashcards

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
