spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: flash
    password: flash
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  jackson:
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    org.springframework: info
    org.hibernate.SQL: info

app:
  jwt:
    issuer: flashcards-app
    secret: "change-this-super-secret-key-please-0123456789"
    expirationMinutes: 120
